### ISSUE TITLE
About prepare data

### ISSUE THREAD

**Issue by sglucas** [jenkspt/gpt-jax#3]
Hi,

When I try to run `prepare.py`, I find there is no space on the device:

`OSError: [Errno 28] No space left on device`

May I ask how to solve the space issue on v3-32?

Best,
Lucas

**Comment by jenkspt** [comment]
The instructions could be better 😄 . I prepared the dataset on a separate worker instance. A few hundred gb of HD space should be enough. Then copy the .tfrecord files to a GCS bucket in the same zone as the v3-32. It's very important to make sure the bucket you're using is in the same zone as the v3-32 instance.

Hope that helps!

**Comment by sglucas** [comment]
hi @jenkspt 

Thanks for your reply. I would like to ask if you could share the GCS bucket of the .tfrecord files. Since I do not have a device with a few hundred gb of HD space. Thanks in advance for your help.

Best,
Lucas

**Comment by jenkspt** [comment]
Can you use a GCS VM? It won't cost much.

**Comment by sglucas** [comment]
Thanks for your help! I can use GCS VM now.

**Comment by sglucas** [comment]
Hi @jenkspt 

I find I cannot run the code successfully now.

The code will stop at this point:

```SSH: Attempting to connect to worker 0...
SSH: Attempting to connect to worker 1...
SSH: Attempting to connect to worker 2...
SSH: Attempting to connect to worker 3...
INFO:root:using config file at config/gpt2.yaml
INFO:root:using config file at config/gpt2.yaml
INFO:root:using config file at config/gpt2.yaml
INFO:root:using config file at config/gpt2.yaml
wandb: Currently logged in as: lucasliunju. Use `wandb login --relogin` to force relogin
wandb: wandb version 0.15.4 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.15.0
wandb: Run data is saved locally in /home/supercomputer_ai/gpt-jax/wandb/run-20230627_081458-f1ojv7yv
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run gpt2_0626_v3_64
wandb: ⭐️ View project at https://wandb.ai/lucasliunju/owt
wandb: 🚀 View run at https://wandb.ai/lucasliunju/owt/runs/f1ojv7yv
INFO:absl:Found no checkpoint directory at gs://lucas_time/vit/gpt2_v3_32_0627/checkpoints/train_state
INFO:absl:Found no checkpoint directory at gs://lucas_time/vit/gpt2_v3_32_0627/checkpoints/train_state
INFO:absl:Found no checkpoint directory at gs://lucas_time/vit/gpt2_v3_32_0627/checkpoints/train_state
PARAMETER COUNT: 124,475,904
INFO:absl:Found no checkpoint directory at gs://lucas_time/vit/gpt2_v3_32_0627/checkpoints/train_state
```


I try to wait 1 hour and I cannot find the training loss in wandb and output log.

**Comment by jenkspt** [comment]
Can you share the exact commands you are running?

**Comment by sglucas** [comment]
Thanks a lot. That does work now.
